language: python
python:
- '3.5'
install: pip install -r requirements.in
script: ./.travis.sh
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_812dd97dd09b_key -iv $encrypted_812dd97dd09b_iv
  -in production.enc -out production -d
- openssl aes-256-cbc -K $encrypted_812dd97dd09b_key -iv $encrypted_812dd97dd09b_iv
  -in preview.enc -out preview -d

