language: python
python:
- '3.5'
install: pip install -r requirements.in
script: ./.travis.sh
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_812dd97dd09b_key -iv $encrypted_812dd97dd09b_iv
  -in .ssh/preview.enc -out .ssh/preview -d
- openssl aes-256-cbc -K $encrypted_812dd97dd09b_key -iv $encrypted_812dd97dd09b_iv
  -in .ssh/production.enc -out .ssh/production -d
