language: python
python:
- '3.5'
install: pip install -r requirements.in
script: ./.travis.sh
before_install:
- openssl aes-256-cbc -K $encrypted_57e34ca198d1_key -iv $encrypted_57e34ca198d1_iv
  -in .ssh/travis.enc -out .ssh/travis -d
branches:
  only:
    - master

